# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-tcg-apply:
    build:
      target: development
    image: ffc-tcg-apply-development
    container_name: ffc-tcg-apply-development
    ports:
      - "3055:3055"
      - "9255:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
