services:
  ffc-tcg-apply:
    build:
      context: .
      target: production
    image: ffc-tcg-apply
    container_name: ffc-tcg-apply
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-apply-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      ELIGIBILITY_TOPIC_ADDRESS: ${ELIGIBILITY_TOPIC_ADDRESS:-ffc-tcg-eligibility-request}${MESSAGE_QUEUE_SUFFIX}
      ELIGIBILITY_SUBSCRIPTION_ADDRESS: ${ELIGIBILITY_SUBSCRIPTION_ADDRESS:-ffc-tcg-eligibility}${MESSAGE_QUEUE_SUFFIX}
      ELIGIBILITYRESPONSE_QUEUE_ADDRESS: ${ELIGIBILITYRESPONSE_QUEUE_ADDRESS:-ffc-tcg-eligibility-response}${MESSAGE_QUEUE_SUFFIX}
      DEFRA_ID_ENABLED: ${DEFRA_ID_ENABLED:-false}
      DEFRA_ID_WELL_KNOWN_URL: ${DEFRA_ID_WELL_KNOWN_URL}
      DEFRA_ID_CLIENT_ID: ${DEFRA_ID_CLIENT_ID}
      DEFRA_ID_CLIENT_SECRET: ${DEFRA_ID_CLIENT_SECRET}
      DEFRA_ID_SERVICE_ID: ${DEFRA_ID_SERVICE_ID}
      DEFRA_ID_POLICY: ${DEFRA_ID_POLICY}
      DEFRA_ID_REDIRECT_URL: ${DEFRA_ID_REDIRECT_URL:-http://localhost:3000/sign-in-oidc}
      DEV_AUTH_PRIVATE_KEY: ${DEV_AUTH_PRIVATE_KEY}
      DEV_AUTH_PUBLIC_KEY: ${DEV_AUTH_PUBLIC_KEY}
      TCG_TEMP_AUTH_COOKIE: ${TCG_TEMP_AUTH_COOKIE}

