{{- include "ffc-helm-library.container-config-map" (list . "ffc-tcg-apply.config-map") -}}
{{- define "ffc-tcg-apply.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  ELIGIBILITY_TOPIC_ADDRESS: {{ .Values.container.eligibilityTopicAddress }}-{{ .Values.environmentCode }}
  ELIGIBILITYRESPONSE_QUEUE_ADDRESS: {{ .Values.container.eligibilityResponseQueueAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  ELIGIBILITY_TOPIC_ADDRESS: {{ quote .Values.container.eligibilityTopicAddress }}
  ELIGIBILITYRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.eligibilityResponseQueueAddress }}
  {{- end }}
  ELIGIBILITY_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.eligibilitySubscriptionAddress }}
  DEFRA_ID_ENABLED: {{ quote .Values.container.defraIdEnabled }}
  DEFRA_ID_WELL_KNOWN_URL: {{ quote .Values.container.defraIdWellKnownUrl }}
  DEFRA_ID_CLIENT_ID: {{ quote .Values.container.defraIdClientId }}  
  DEFRA_ID_SERVICE_ID: {{ quote .Values.container.defraIdServiceId }}
  DEFRA_ID_POLICY: {{ quote .Values.container.defraIdPolicy }}
  {{- if .Values.pr }}
  DEFRA_ID_REDIRECT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}/{{ .Values.container.defraIdRedirectUrl }}
  {{ else }}
  DEFRA_ID_REDIRECT_URL: https://{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}/{{ .Values.container.defraIdRedirectUrl }}
  {{- end }}
  {{- if and (.Values.environmentCode) (ne (.Values.environmentCode | toString ) "snd") }}
  API_ENDPOINT: {{ .Values.container.apiEndpoint }}-{{ .Values.environmentCode }}.{{ .Values.ingress.server }}
  {{ else }}
  API_ENDPOINT: {{ .Values.container.sndEndpoint }}
  {{- end }}
  {{- if (eq (.Values.environmentCode | toString ) "snd") }}
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  {{- end }}
{{- end -}}
