#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ffc-tcg$ --format={{.Name}})" ]; then
  echo "Creating ffc-tcg Docker network"
  docker network create ffc-tcg
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

mkdir -p .ssh

if [ ! -f .ssh/ssh_rsa_key ]; then
  echo "Generating SSH keys"
  ssh-keygen -t rsa -b 4096 -f .ssh/ssh_rsa_key < /dev/null
fi

export DEV_AUTH_PRIVATE_KEY=$(cat .ssh/ssh_rsa_key)
export DEV_AUTH_PUBLIC_KEY=$(cat .ssh/ssh_rsa_key.pub)

docker-compose down

docker-compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  -f docker-compose.link.yaml \
  up $@
