environment: production
environmentCode:
name: ffc-tcg-apply
namespace: ffc-tcg
workstream: ffc-tcg
image: ffc-tcg-apply

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-tcg-apply-config-map

containerSecret:
  name: ffc-tcg-apply-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3055
  messageQueueHost: namespace.servicebus.windows.net
  eligibilityTopicAddress: ffc-tcg-eligibility-request
  eligibilitySubscriptionAddress: ffc-tcg-eligibility
  eligibilityResponseQueueAddress: ffc-tcg-eligibility-response
  defraIdEnabled: true
  defraIdWellKnownUrl: not-a-real-url
  defraIdClientId: not-a-real-clientID
  defraIdClientSecret: not-a-real-clientSecret
  defraIdServiceId: not-a-real-serviceID
  defraIdPolicy: not-a-real-policy
  defraIdRedirectUrl: sign-in-oidc

livenessProbe:
  path: /healthz
  port: 3055
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3055
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

ingress:
  class: nginx
  endpoint: ffc-tcg-apply
  server: example.com

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
